import * as React from "react"
import { cva, type VariantProps } from "class-variance-authority"
import { Slot } from "radix-ui"

import { cn } from "@/lib/utils"

// Heads up: this file was generated by the shadcn/ui CLI (`shadcn add`), not
// hand-written from scratch — that's why it lives in components/ui rather
// than the app-specific folders. It's yours to edit freely, but if you ever
// re-run the CLI to update this component, it may overwrite these comments.

// cva ("class variance authority") builds a function that returns a string
// of Tailwind classes based on which "variant" you pick. The long string
// below is the base classes applied to every button, no matter the variant.
const buttonVariants = cva(
  "group/button inline-flex shrink-0 items-center justify-center rounded-lg border border-transparent bg-clip-padding text-sm font-medium whitespace-nowrap transition-all outline-none select-none focus-visible:border-ring focus-visible:ring-3 focus-visible:ring-ring/50 active:not-aria-[haspopup]:translate-y-px disabled:pointer-events-none disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-3 aria-invalid:ring-destructive/20 dark:aria-invalid:border-destructive/50 dark:aria-invalid:ring-destructive/40 [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    // Each key under `variants` becomes a prop you can pass to <Button>.
    // e.g. <Button variant="outline" size="sm" /> picks one class string
    // from each group below and merges them together.
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/80",
        outline:
          "border-border bg-background hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:border-input dark:bg-input/30 dark:hover:bg-input/50",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-[color-mix(in_oklch,var(--secondary),var(--foreground)_5%)] aria-expanded:bg-secondary aria-expanded:text-secondary-foreground",
        ghost:
          "hover:bg-muted hover:text-foreground aria-expanded:bg-muted aria-expanded:text-foreground dark:hover:bg-muted/50",
        destructive:
          "bg-destructive/10 text-destructive hover:bg-destructive/20 focus-visible:border-destructive/40 focus-visible:ring-destructive/20 dark:bg-destructive/20 dark:hover:bg-destructive/30 dark:focus-visible:ring-destructive/40",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-8 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        xs: "h-6 gap-1 rounded-[min(var(--radius-md),10px)] px-2 text-xs in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-7 gap-1 rounded-[min(var(--radius-md),12px)] px-2.5 text-[0.8rem] in-data-[slot=button-group]:rounded-lg has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3.5",
        lg: "h-9 gap-1.5 px-2.5 has-data-[icon=inline-end]:pr-2 has-data-[icon=inline-start]:pl-2",
        icon: "size-8",
        "icon-xs":
          "size-6 rounded-[min(var(--radius-md),10px)] in-data-[slot=button-group]:rounded-lg [&_svg:not([class*='size-'])]:size-3",
        "icon-sm":
          "size-7 rounded-[min(var(--radius-md),12px)] in-data-[slot=button-group]:rounded-lg",
        "icon-lg": "size-9",
      },
    },
    // If you don't pass variant/size at all, these are what you get.
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

// This is a normal React component (a function returning JSX), but with a
// few patterns you'll see constantly in real component libraries:
function Button({
  // Destructuring the props object pulls out each named prop, and `= "..."`
  // gives it a default value when the caller doesn't pass one.
  className,
  variant = "default",
  size = "default",
  asChild = false,
  // `...props` ("rest syntax") collects every *other* prop the caller passed
  // (onClick, disabled, type, etc.) into one object, so we don't have to
  // list every possible <button> attribute by hand — see the spread below.
  ...props
}: React.ComponentProps<"button"> &          // all the normal <button> props
  VariantProps<typeof buttonVariants> & {    // + "variant" and "size" from cva
    asChild?: boolean
  }) {
  // asChild is a common shadcn/Radix pattern: normally this renders a real
  // <button>, but if a caller passes asChild (e.g. to make a <Link> look
  // like a button), Slot.Root instead merges these props onto whatever
  // single child element is passed in, rather than wrapping it in a <button>.
  const Comp = asChild ? Slot.Root : "button"

  return (
    <Comp
      data-slot="button"
      data-variant={variant}
      data-size={size}
      // Look up the right classes for this variant/size combo, then merge
      // in any extra className the caller passed (e.g. <Button className="w-full" />).
      className={cn(buttonVariants({ variant, size, className }))}
      // Spreads onClick, disabled, type, aria-*, etc. straight onto the
      // underlying element — this is how the component stays a drop-in
      // replacement for a plain <button>.
      {...props}
    />
  )
}

// Exporting both lets other files use <Button /> directly, or reuse
// buttonVariants() to style a non-<button> element the same way.
export { Button, buttonVariants }
